app_core/urls.py
from django.urls import path
from . import views

app_name='app_core'
urlpatterns =[
    path('', views.home, name='home'),
    path('product/<int:pk>/', views.product, name='product')
]

backend/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app_core.urls', namespace='app_core')),
    path("__reload__/", include("django_browser_reload.urls")),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

app_core/models.py
from django.db import models

# Create your models here.

app_core/views.py
from django.shortcuts import render
import requests

def home(request):
    # response = requests.get("https://fakestoreapi.com/products?limit=20")
    # products = response.json()
    # response = requests.get("https://api.escuelajs.co/api/v1/products")
    # products = response.json()
    response = requests.get("https://dummyjson.com/products")
    data = response.json()

    products = []
    if 'products' in data:
        for product in data['products']:
            id = product['id']
            title = product['title']
            description = product['description']
            price = product['price']
            image = product['images'][0]
            
            products.append({
                'id': id,
                'title': title,
                'description': description,
                'price': price,
                'image': image
            })
    else:
        print("Nie udało się pobrać danych produktów")
            
    
    return render(request, 'home.html', {'products': products})

def product(request, pk):
    # response = requests.get("http://fakestoreapi.com/products/{}".format(id))
    # product = response.json()
    response = requests.get(f"https://dummyjson.com/products/{pk}")
    product = response.json()
    
    return render(request, 'product.html', {'product': product})

templates/base.html
{% load static %} {% load static tailwind_tags %}
<!DOCTYPE html>
<html 
  lang="en" 
  x-data="{ darkMode: localStorage.getItem('dark') === 'true', open: false }" 
  x-init="$watch('darkMode', value => localStorage.setItem('dark', value))" 
  :class="{ 'dark': darkMode, 'light': !darkMode }"
>
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="icon" href="{% static 'amazon-svgrepo-com.svg' %}" sizes="64x64" type="image/png" />
    <script>
      function isDarkModeEnabled() {
        const darkMode = localStorage.getItem('dark')
        return darkMode === 'true'
      }
      function applyDarkModeClass() {
        if (isDarkModeEnabled()) {
          document.documentElement.classList.add('dark')
        } else {
          document.documentElement.classList.remove('dark')
        }
      }
      applyDarkModeClass()
    </script>
    <script defer src="https://cdn.jsdelivr.net/npm/alpinejs@3.x.x/dist/cdn.min.js"></script>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Concert+One&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/dist/styles.css' %}" />
    <style type="text/tailwindcss">
      [x-cloak] {
        display: none !important;
      }
    </style>
    <title>Amazon - clone</title>
    {% tailwind_css %}
  </head>
  <body class="cursor-default min-w-[400px] bg-white dark:bg-[#2B2D31] grid grid-cols-4 min-h-screen transition-all">
    {% include 'includes/header.html' %}
      {% block content %}

      {% endblock %}
    {% include 'includes/footer.html' %}
  </body>
</html>

templates/home.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
  <main class="col-span-full dark:bg-[#1E1F22] rounded-lg max-w-screen-2xl 2xl:mx-auto">
    <section class="flex justify-evenly flex-wrap p-2 min-h-screen bg-gradient-to-b from-orange-600 to-40% to-transparent">
      <banner class="w-full h-[300px] lg:h-[400px] 2xl:h-[500px] bg-cover mt-1 mb-10 rounded bg-no-repeat" style="background-image: url('{% static 'banner.png' %}');"></banner>
      {% for product in products|slice:':14' %}
        <div class="product flex flex-col m-2 p-2 basis-11/12 sm:basis-5/12 lg:basis-3/12 2xl:basis-1/5 flex-grow items-center bg-gradient-to-b from-gray-300 to-[whitesmoke] dark:from-gray-700 dark:to-[#2B2D31] rounded-lg hover:opacity-95 transition">
           <a class="h-[400px] sm:h-[350px] md:h-[300px] lg:h-[250px] w-full" href="{% url 'app_core:product' product.id %}">
            <img class="h-full w-full mx-auto object-contain rounded-lg bg-white cursor-pointer" src="{{ product.image }}" alt="" />
           </a>
           <a href="{% url 'app_core:product' product.id %}">
             <h3 class="font-bold text-center text-black dark:text-white mt-2">{{ product.title }}</h3>
           </a>
           <a href="{% url 'app_core:product' product.id %}">
             <p class="dark:text-white mt-2 mb-4">{{ product.description|truncatewords:10 }}</p>
           </a>
          <button class="btn mt-auto">dodaj do koszyka</button>
        </div>
      {% endfor %}
    </section>
  </main>
{% endblock %}

templates/includes/footer.html
<footer class="col-span-full bg-[whitesmoke] dark:bg-[#0F172A] mt-6 p-2">
  <div class="flex justify-center items-center dark:text-white font-bold text-xs sm:text-sm md:text-base">
    <!-- prettier-ignore-start -->
    Created by <a href="https://kr0pa.pl" target="_blank"><p class="text-[royalblue] mx-1 cursor-pointer text-sm sm:text-base md:text-lg">kr0pa</p></a> educational <p class="mx-1 text-sm sm:text-base md:text-lg">Amazon Clone</p>&copy; 2024

  </div>
</footer>

templates/includes/header.html
{% load static %}
<header class="h-14 col-span-full flex justify-between items-center p-2 bg-[whitesmoke] dark:bg-[#0F172A] transition-all relative">
  <a href="/">
    <img class="h-8 object-contain" x-bind:src="!darkMode ? '{% static 'amazon_logo1.png' %}' : '{% static 'amazon_logo2.png' %}'" alt="" />
  </a>
    
  <div class="flex items-center">
    <img class="h-8 mr-4 cursor-pointer" x-on:click="darkMode = !darkMode" x-bind:src="darkMode ? 'https://img.icons8.com/ultraviolet/40/moon.png' : 'https://img.icons8.com/emoji/48/sun-emoji.png'" />

    <img class="h-8 mr-4" src="https://img.icons8.com/external-flaticons-flat-flat-icons/64/external-basket-web-flaticons-flat-flat-icons-3.png" />

    <img x-on:click="open = !open" class="block md:hidden h-7 translate-y- select-none cursor-pointer mr-2 z-[2]" x-bind:src="!open ? (darkMode ? 'https://img.icons8.com/small/64/FFFFFF/menu.png' : 'https://img.icons8.com/small/64/menu.png') : (darkMode ? 'https://img.icons8.com/small/64/FFFFFF/delete-sign.png' : 'https://img.icons8.com/small/64/delete-sign.png')" />

    <nav 
    x-show="open" 
    x-init="() => {
      window.addEventListener('resize', () => {
        isMdOrLarger = window.innerWidth >= 768;
        if (isMdOrLarger) {
          open = false;
        }
      });
    }" 
    x-cloak 
    class="lex-grow bg-[whitesmoke] dark:bg-[#2B2D31] h-screen w-screen md:mt-0 absolute top-0 left-0" x-transition:enter="duration-300 ease-out" x-transition:enter-start="opacity-0 -translate-y-3/4" x-transition:enter-end="opacity-100 translate-y-0" x-transition:leave="duration-300 ease-in-out" x-transition:leave-start="opacity-100 translate-y-0" x-transition:leave-end="opacity-0 -translate-y-3/4">
      <ul class="flex flex-col justify-center items-center h-full text-4xl dark:text-white mobileClass">
        <li x-on:click="open = false">Profil</li>
        <li x-on:click="open = false">Edycja</li>
        <li x-on:click="open = false">{{ user.is_authenticated|yesno:'Wyloguj się,  Zaloguj się' }}</li>
      </ul>

      <img class="absolute top-1/4 left-1/2 -translate-x-1/2 -translate-y-1/2 h-28 object-contain cursor-default" x-bind:src="!darkMode ? '{% static 'amazon_logo1.png' %}' : '{% static 'amazon_logo2.png' %}'" alt="" />
    </nav>
  </div>
</header>

theme/templates/base.html
{% load static tailwind_tags %}
<!DOCTYPE html>
<html lang="en">
	<head>
    <title>Django Tailwind</title>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<meta http-equiv="X-UA-Compatible" content="ie=edge">
		{% tailwind_css %}
	</head>

	<body class="bg-gray-50 font-serif leading-normal tracking-normal">
		<div class="container mx-auto">
			<section class="flex items-center justify-center h-screen">
				<h1 class="text-5xl">Django + Tailwind = ❤️</h1>
			</section>
		</div>
	</body>
</html>